FROM apache/hive:4.0.0

COPY drivers/postgresql-42.7.3.jar /opt/hive/lib/postgresql-42.7.3.jar
COPY drivers/hadoop-aws-3.3.2.jar /opt/hive/lib/hadoop-aws-3.3.2.jar
COPY drivers/aws-java-sdk-bundle-1.11.1026.jar /opt/hive/lib/aws-java-sdk-bundle-1.11.1026.jar
